# Generated by Django 6.0.3 on 2026-03-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("immatriculation", models.CharField(max_length=32, unique=True)),
                ("capacite", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BUS", "Bus"),
                            ("MINIBUS", "Minibus"),
                            ("VAN", "Van"),
                            ("BERLINE", "Berline"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "transporteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicules",
                        to="users.transporteur",
                    ),
                ),
            ],
        ),
    ]
