# Generated by Django 6.0.3 on 2026-03-22 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicules", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ville_depart",
                    models.CharField(max_length=100, verbose_name="Ville de départ"),
                ),
                (
                    "ville_arrivee",
                    models.CharField(max_length=100, verbose_name="Ville d'arrivée"),
                ),
                ("distance_km", models.FloatField(verbose_name="Distance (km)")),
                ("duree_estimee", models.DurationField(verbose_name="Durée estimée")),
                ("date_depart", models.DateField(verbose_name="Date de départ")),
                ("heure_depart", models.TimeField(verbose_name="Heure de départ")),
                (
                    "date_arrivee_estimee",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date/Heure d'arrivée estimée",
                    ),
                ),
                (
                    "date_arrivee_reelle",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date/Heure d'arrivée réelle",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Prix"
                    ),
                ),
                (
                    "nombre_places_disponibles",
                    models.PositiveIntegerField(
                        verbose_name="Nombre de places disponibles"
                    ),
                ),
                (
                    "places_totales",
                    models.PositiveIntegerField(verbose_name="Places totales"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "points_arret",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Points d'arrêt"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "transporteur",
                    models.ForeignKey(
                        limit_choices_to={"role": "driver"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trajets_transporteur",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Transporteur",
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajets",
                        to="vehicules.vehicule",
                        verbose_name="Véhicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trajet",
                "verbose_name_plural": "Trajets",
                "ordering": ["-date_depart"],
                "indexes": [
                    models.Index(
                        fields=["statut"], name="trajets_tra_statut_99a975_idx"
                    ),
                    models.Index(
                        fields=["date_depart"], name="trajets_tra_date_de_1e4c63_idx"
                    ),
                    models.Index(
                        fields=["ville_depart"], name="trajets_tra_ville_d_77c938_idx"
                    ),
                    models.Index(
                        fields=["ville_arrivee"], name="trajets_tra_ville_a_dcd174_idx"
                    ),
                ],
            },
        ),
    ]
