# Generated by Django 6.0.3 on 2026-03-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=200)),
                ('heure_prevue', models.DateTimeField()),
                ('heure_reelle', models.DateTimeField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Étape',
                'verbose_name_plural': 'Étapes',
                'ordering': ['trajet', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=200, verbose_name='Lieu de départ')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('date_depart', models.DateTimeField(verbose_name='Date et heure de départ')),
                ('date_arrivee_estimee', models.DateTimeField(blank=True, null=True, verbose_name="Date et heure d'arrivée estimée")),
                ('date_arrivee_reelle', models.DateTimeField(blank=True, null=True, verbose_name="Date et heure d'arrivée réelle")),
                ('places_totales', models.PositiveIntegerField(verbose_name='Nombre total de places')),
                ('places_disponibles', models.PositiveIntegerField(verbose_name='Places disponibles')),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par place')),
                ('distance_km', models.FloatField(blank=True, null=True, verbose_name='Distance (km)')),
                ('duree_estimee', models.DurationField(blank=True, null=True, verbose_name='Durée estimée')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('complet', 'Complet'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='actif', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude_depart', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_depart', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude_arrivee', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_arrivee', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('points_arret', models.JSONField(blank=True, default=list, verbose_name="Points d'arrêt")),
                ('arrets', models.JSONField(blank=True, default=list, verbose_name='Liste des arrêts')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'ordering': ['-date_depart'],
            },
        ),
    ]
