# Generated by Django 6.0.3 on 2026-03-24 02:15

import django.db.models.deletion
from django.db import migrations, models


def ensure_etape_table_if_missing(apps, schema_editor):
    """
    Bases où une ancienne 0001_initial n'avait créé que Trajet (sans Etape) :
    AddField sur Etape échoue si la table n'existe pas.
    """
    conn = schema_editor.connection
    if "trajets_etape" in conn.introspection.table_names():
        return
    with conn.cursor() as cursor:
        if conn.vendor == "sqlite":
            cursor.execute(
                '''
                CREATE TABLE "trajets_etape" (
                    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    "lieu" varchar(200) NOT NULL,
                    "heure_prevue" datetime NOT NULL,
                    "heure_reelle" datetime NULL,
                    "ordre" integer unsigned NOT NULL CHECK ("ordre" >= 0)
                );
                '''
            )
        elif conn.vendor == "postgresql":
            cursor.execute(
                '''
                CREATE TABLE "trajets_etape" (
                    "id" bigserial NOT NULL PRIMARY KEY,
                    "lieu" varchar(200) NOT NULL,
                    "heure_prevue" timestamp with time zone NOT NULL,
                    "heure_reelle" timestamp with time zone NULL,
                    "ordre" integer NOT NULL CHECK ("ordre" >= 0)
                );
                '''
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0001_initial'),
        ('users', '0001_initial'),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ensure_etape_table_if_missing, noop_reverse),
        migrations.AddField(
            model_name='trajet',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajets_conduits', to='users.transporteur', verbose_name='Chauffeur'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='transporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='users.transporteur'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='vehicules.vehicule', verbose_name='Véhicule'),
        ),
        migrations.AddField(
            model_name='etape',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='trajets.trajet'),
        ),
        migrations.AddIndex(
            model_name='trajet',
            index=models.Index(fields=['statut'], name='trajets_tra_statut_99a975_idx'),
        ),
        migrations.AddIndex(
            model_name='trajet',
            index=models.Index(fields=['date_depart'], name='trajets_tra_date_de_1e4c63_idx'),
        ),
    ]
