# Generated by Django 6.0.3 on 2026-03-24 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trajets', '0001_initial'),
        ('users', '0001_initial'),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajets_conduits', to='users.transporteur', verbose_name='Chauffeur'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='transporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='users.transporteur'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='vehicules.vehicule', verbose_name='Véhicule'),
        ),
        migrations.AddField(
            model_name='etape',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='trajets.trajet'),
        ),
        migrations.AddIndex(
            model_name='trajet',
            index=models.Index(fields=['statut'], name='trajets_tra_statut_99a975_idx'),
        ),
        migrations.AddIndex(
            model_name='trajet',
            index=models.Index(fields=['date_depart'], name='trajets_tra_date_de_1e4c63_idx'),
        ),
    ]
