# Generated by Django 6.0.3 on 2026-05-17 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trajets", "0003_trajet_validation_admin"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="trajet",
            new_name="trajets_tra_validat_8096b0_idx",
            old_name="trajets_tra_validat_idx",
        ),
    ]
