# Generated by Django 6.0.3 on 2026-03-24 02:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('passager', 'Passager'), ('transporteur', 'Transporteur'), ('admin', 'Administrateur')], default='passager', max_length=20, verbose_name='Rôle')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('niveau_acces', models.CharField(choices=[('complet', 'Accès complet'), ('moderation', 'Modération seule'), ('lecture', 'Lecture seule')], default='complet', max_length=20, verbose_name="Niveau d'accès")),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='passager_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preferences_siege', models.CharField(choices=[('fenetre', 'Fenêtre'), ('couloir', 'Couloir'), ('indifferent', 'Indifférent')], default='indifferent', max_length=20, verbose_name='Préférence de siège')),
                ('notifications_activees', models.BooleanField(default=True, verbose_name='Notifications actives')),
                ('points_fidelite', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Passager',
                'verbose_name_plural': 'Passagers',
            },
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transporteur_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom_entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('numero_licence', models.CharField(max_length=50, unique=True, verbose_name='Numéro de licence')),
                ('verifie', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('note_moyenne', models.FloatField(default=0.0, verbose_name='Note moyenne')),
                ('licence_pdf', models.FileField(blank=True, upload_to='licences/')),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('est_ouvert', models.BooleanField(default=True, verbose_name='Accepte les réservations')),
            ],
            options={
                'verbose_name': 'Transporteur',
                'verbose_name_plural': 'Transporteurs',
            },
        ),
    ]
