# Generated by Django 6.0.3 on 2026-03-28 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("carte", "Carte"),
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile money"),
                            ("virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("echoue", "Échoué"),
                            ("rembourse", "Remboursé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-date_paiement"],
            },
        ),
    ]
