# Generated by Django 6.0.3 on 2026-03-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("paiements", "0001_initial"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paiements",
                to="reservations.reservation",
            ),
        ),
    ]
