# Generated by Django 6.0.3 on 2026-03-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville_depart", models.CharField(max_length=150)),
                ("ville_arrivee", models.CharField(max_length=150)),
                ("date_depart", models.DateField()),
                ("heure_depart", models.TimeField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nombre_places_disponibles", models.PositiveIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("ouvert", "Ouvert aux réservations"),
                            ("complet", "Complet"),
                            ("annule", "Annulé"),
                            ("termine", "Terminé"),
                        ],
                        default="ouvert",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["date_depart", "heure_depart"],
            },
        ),
    ]
