# Generated by Django 6.0.3 on 2026-03-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trajets", "0001_initial"),
        ("users", "0001_initial"),
        ("vehicules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trajet",
            name="transporteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trajets",
                to="users.transporteur",
            ),
        ),
        migrations.AddField(
            model_name="trajet",
            name="vehicule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trajets",
                to="vehicules.vehicule",
            ),
        ),
    ]
