# Generated by Django 6.0.3 on 2026-03-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_qr', models.CharField(max_length=255, unique=True)),
                ('pdf', models.FileField(blank=True, upload_to='billets/')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Billet',
                'verbose_name_plural': 'Billets',
            },
        ),
        migrations.CreateModel(
            name='PointRamassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('instructions', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Point de ramassage',
                'verbose_name_plural': 'Points de ramassage',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_places', models.PositiveIntegerField(default=1)),
                ('numero_siege', models.CharField(blank=True, max_length=10)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('recupere', models.BooleanField(default=False, verbose_name='Passager récupéré')),
                ('heure_recuperation', models.DateTimeField(blank=True, null=True)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
    ]
