# Generated by Django 6.0.3 on 2026-03-24 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('trajets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='passager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.passager'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trajets.trajet'),
        ),
        migrations.AddField(
            model_name='pointramassage',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ramassage', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='billet',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billet', to='reservations.reservation'),
        ),
    ]
