# Generated by Django 6.0.3 on 2026-03-22 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=50, verbose_name="Marque")),
                ("modele", models.CharField(max_length=50, verbose_name="Modèle")),
                (
                    "plaque_immatriculation",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Plaque d'immatriculation",
                    ),
                ),
                (
                    "numero_chassis",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro de chassis"
                    ),
                ),
                (
                    "type_vehicule",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("minibus", "Minibus"),
                            ("voiture", "Voiture"),
                            ("van", "Van"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "capacite",
                    models.PositiveIntegerField(verbose_name="Capacité (places)"),
                ),
                (
                    "annee_fabrication",
                    models.IntegerField(verbose_name="Année de fabrication"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_trajet", "En trajet"),
                            ("maintenance", "Maintenance"),
                            ("inactif", "Inactif"),
                        ],
                        default="disponible",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("couleur", models.CharField(max_length=30, verbose_name="Couleur")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vehicules/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "assurance_date_expiration",
                    models.DateField(verbose_name="Date expiration assurance"),
                ),
                (
                    "controle_technique_date",
                    models.DateField(verbose_name="Date contrôle technique"),
                ),
                (
                    "kilometrage",
                    models.IntegerField(default=0, verbose_name="Kilométrage"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "chauffeur",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "driver"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicule",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chauffeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
                "ordering": ["-date_creation"],
            },
        ),
    ]
