# Generated by Django 6.0.3 on 2026-03-24 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='marques/')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_places', models.PositiveIntegerField(default=4)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='vehicules.marque')),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'unique_together': {('marque', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('annee', models.PositiveIntegerField(verbose_name='Année de mise en circulation')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('en_maintenance', models.BooleanField(default=False, verbose_name='En maintenance')),
                ('climatisation', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('prise_usb', models.BooleanField(default=False)),
                ('espace_bagages', models.CharField(blank=True, max_length=100)),
                ('photo_principale', models.ImageField(blank=True, upload_to='vehicules/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicules.modele')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='users.transporteur')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
    ]
