# Generated by Django 6.0.3 on 2026-03-28 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("reservation", "Réservation"),
                            ("paiement", "Paiement"),
                            ("systeme", "Système"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_envoi", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-date_envoi"],
            },
        ),
    ]
