# Generated by Django 6.0.3 on 2026-03-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                (
                    "plaque_immatriculation",
                    models.CharField(max_length=20, unique=True),
                ),
                ("capacite", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_cours", "En cours"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transport",
                "verbose_name_plural": "Transports",
                "ordering": ["-date_creation"],
            },
        ),
    ]
